### ISSUE TITLE
linear model simulation

### ISSUE THREAD

**Issue by mataddy** [TaddyLab/gamma_lasso#2]
hi @LuciusJiang,

let's switch to communicating in github rather than in email so we can keep track.

to summarize the current state of this issue from our emails, you have re-run a bunch of the simulations under different coefficient decay, as plotted here
<img width="590" alt="screen shot 2015-07-07 at 3 03 42 pm" src="https://cloud.githubusercontent.com/assets/4673515/8546605/85a9c8a2-24b9-11e5-83b9-167a05bc44a5.png">

These current simulations have different numbers of parameters involved (vertical lines on above plot I believe); I'd prefer to keep them all at l=200, as I believe is done with current decay factor of 50.

**Comment by mataddy** [comment]
From @LuciusJiang  in email "I simulated with l=200 for decay=10 and 100. The results remained the same. So probably the “l" does not affect the r^2."

**Comment by mataddy** [comment]
Thanks, this makes sense to me.  Looking at the code, the 'l' just determines the space over which we search for the optimal L0 penalized model.  I had misunderstood and thought it was being used somewhere in data generation.

**Comment by LuciusJiang** [comment]
@TaddyLab/owners I am happy to do more simulation jobs if you need? If possible, I think I need several days to go through the paper and try to understand your theories and ideas.

**Comment by mataddy** [comment]
thanks much @LuciusJiang, this is great work so far.

I've added a supplemental document at /tex/supplemental.tex.  Can you add your tables in there as you go, starting with the ones you've already created?  Many thanks.

And yes, lets do some more simulations.  For the next ones, I'd like to see all of the remaining combinations for the 'sparsity' and 'decay' that I mention in the supplental doc.  We can consider the existing decay sets, and add to those 'sparsity' settings of s=0.1 and s=0.9.  Finally, my idea is that at the end we'll repeat the same simulations for logistic regression where the 0/1 response is defined via y>0 for y generated using the same data generating process we're currently using.

Please feel free to take your time reading through the paper before proceeding.  I'm in town next week if you want to chat.

PS now that you are part of my github or, you can just check out and work on this repo directly instead of forking, if you prefer.

**Comment by LuciusJiang** [comment]
@TaddyLab/owners Is it possible that I can come to your office to talk with you about the simulation on Jul 14th(Tue) since it is the due day for PBHS 32100 (Introduction to Biostatistics) HW1 and I need to grade their homework. My time schedule after 3:30 p.m. everyday is quite flexible. So I can come to your office first then go to Biostat department.

**Comment by mataddy** [comment]
great, let's say 330 pm central on Tuesday

**Comment by LuciusJiang** [comment]
@TaddyLab/owners When comes to Bin(p=0), it shows "Error: lambda.min.ratio <= 1 is not TRUE". So can I try p=0.1, 0.5 and 0.9 instead?

**Comment by LuciusJiang** [comment]
When comes to loop, R becomes quite slow. You know, we have s2n=0.5,1,2; rho=0,0.5,0.9, p=0.1,0.5,0.9 and decay=10,50,100. It costed 40 minutes to run all the possible parameters (s2n, rho, p, decay) for one time. Do you need me to try 1000 times? It will take me 27 days to finish the simulation job,haha!

**Comment by mataddy** [comment]
hey hao,

p=.1 is fine.

on the other question: I can see you up to run on a grid, so we can run all
1000 at the same time.  do you have a uchicago account?

but also, I'm not sure why it takes so long.  can you please set the code
to check time for each data/algorithm pair on a single run and let me know
how long each takes?  thanks

**Comment by LuciusJiang** [comment]
I will try it today!

**Comment by LuciusJiang** [comment]
Hi Matt,
Sorry for my late work. For the last half month, I did a lot of simulations to make sure that there is no mistakes in my work. I have already updated the R^2 and FDR tables and sent you a email with 81 plots attached.
Sorry again for my late work!

**Comment by mataddy** [comment]
Hi @LuciusJiang , no problem at all!  Thanks for all of the work!  I've been traveling and haven't had a chance to look through the results yet but will asap.  I'm back in chicago in early september; when are you in town?

**Comment by LuciusJiang** [comment]
Hi @mataddy 
Since now I am still working as an intern in Marquette Partners (a great trading firm) in Chicago downtown, I will definitely stay in Chicago in next month. But I want to go to NY to visit Sen and stay there for a week in the end of Sep before the new quarter. But if you need me to stay in Chicago for research job, I am totally fine since I haven't booked the flight tickets yet. I am happy to work with you on the project.

**Comment by mataddy** [comment]
sounds great; don't change any travel plans on my account.  we can chat at beginning of September

**Comment by mataddy** [comment]
Hi @LuciusJiang , just looked through the results;  great work, and much thanks for this.  How long did it take to run?

If you have time and are looking to do some more before september, it would be great to repeat the analysis for binary response, say 'yb', and with logistic (rather than linear) regression.

My first guess as to how to do this would be to simply threshold the values for y from our current data generating process.  We could map all yb = ifelse(y<0,0,1). 

Let me know if you are interested in doing this; I'll open a new issue for it if you are.

**Comment by LuciusJiang** [comment]
@mataddy 
I did not use RCC but the server in my company. I will use the RCC to do the simulation again as soon as possible.

I'd like try the binary version. When comes to the evaluation jobs about model fitting,what kinds of criterions do you want?

**Comment by mataddy** [comment]
@LuciusJiang I just opened a new issue for this.  Also, no need to re-run the existing results on RCC.  If you can just put all of the output of your runs into a folder on RCC (e.g., in your home directory there) then that is all I'll need.

**Comment by LuciusJiang** [comment]
@mataddy 
I will do it soon.
